Remove Thermal Regulators
The-Merchants-Guild/Merchant-Station-13 pull request #142
Opened 2022-04-18 21:28 UTC by KangTut

## About The Pull Request
Removes the thermal regulator from spacesuits and hardsuits as well as any associated code

## Why It's Good For The Game
There isn't anything fun about having to keep track of a suits power charge. Going space exploring shouldn't mean that you either need to grab and charge a high tech cell or carry several backups. It was just more pointless and tedious crap added for no adequate reason.

## Changelog
-Removes the need to toggle your spacesuit's ability to protect you from space
-Removes power cells and anything related to them from space and hardsuits
-Removes EMP effects on hardsuits

2022-04-21 14:56 UTC, TheChosenEvilOne reviewed
just one thing, otherwise seems good.

2022-04-22 18:09 UTC, TheChosenEvilOne requested changes
one more thing.

2022-04-22 18:09 UTC, TheChosenEvilOne commented on code/datums/action.dm
>  /datum/action/item_action/toggle_spacesuit
remove this datum completely.

2022-04-22 19:47 UTC, KangTut commented on code/datums/action.dm
>  /datum/action/item_action/toggle_spacesuit
Thanks for helping me with this.

2022-04-23 14:55 UTC, EdgeLordExe commented on code/modules/clothing/spacesuits/_spacesuits.dm
> +	min_cold_protection_temperature = SPACE_SUIT_MIN_TEMP_PROTECT
this seems to be doubled for no reason

2022-04-24 09:53 UTC, TheChosenEvilOne approved these changes
lgtm

2022-04-25 04:24 UTC, merged