[Port From Bee] Syndicate Teleporter
The-Merchants-Guild/Merchant-Station-13 pull request #303
Opened 2022-06-22 14:39 UTC by eeSPee

## About The Pull Request

It's spelunki's hand teleporter. Teleports you forward on use. When teleported in a wall, teleports you again. If that fails, you get gibbed.

https://github.com/BeeStation/BeeStation-Hornet/pull/3372

## Changelog
:cl:
add: Syndicate teleporter in uplinks
/:cl:

2022-06-26 09:09 UTC, MACIEKBAKI requested changes
just replace all `"<span class='CLASSNAME'>TEXT HERE</span>"` with `span_CLASSNAME("TEXT HERE")` and I think it'll be good

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +	. += "<span class='notice'>[src] has [charges] out of [max_charges] charges left.</span>"
`	. += span_notice("[src] has [charges] out of [max_charges] charges left.")`

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +			to_chat(user, "<span class='danger'>[src] buzzes and activates!</span>")
`to_chat(user, span_danger("[src] buzzes and activates!"))`

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +		to_chat(user, "<span class='warning'>[src] is still recharging.</span>")
`to_chat(user, span_warning("[src] is still recharging."))`

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +			visible_message("<span class='warning'>[src] activates and blinks out of existence!</span>")
`visible_message(span_warning("[src] activates and blinks out of existence!"))`

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +		to_chat(user, "<span class='notice'>\The [src] is malfunctioning.</span>")
`to_chat(user, span_notice("\The [src] is malfunctioning."))`

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +	to_chat(user, "<span class='userdanger'>You teleport into the wall, the teleporter tries to save you, but-</span>")
`to_chat(user, span_userdanger("You teleport into the wall, the teleporter tries to save you, but-"))`

2022-06-26 09:09 UTC, MACIEKBAKI commented on code/game/objects/items/teleportation.dm
> +		to_chat(M, "<span class='userdanger'>[user] teleports into you, knocking you to the floor with the bluespace wave!</span>")
`to_chat(M, span_userdanger("[user] teleports into you, knocking you to the floor with the bluespace wave!"))`

2022-06-26 09:14 UTC, MACIEKBAKI commented
If you want a very simple and lazy way to replace the spans with span defines, go to a regex testing site like [regex101](url), go into substitution, use the regular expression `"<span class='(.+)'>(.+)<\/span>"` and replacement string `span_$1("$2")` and paste the code into the test string, then just copy the output and it should work without major issues.

2022-06-26 19:40 UTC, eeSPee commented
Thanks, @MACIEKBAKI

Should be fixed now.

2022-06-29 11:06 UTC, MACIEKBAKI approved these changes

2022-06-29 11:07 UTC, merged