Named Vomit
The-Merchants-Guild/Merchant-Station-13 pull request #4
Opened 2021-08-02 20:09 UTC by Bucovineanu

## About The Pull Request

Small chance for vomit to have a name

## Why It's Good For The Game

Because it's funny

## Changelog
:cl:
add: Some vomit may be named after famous trash.
/:cl:

2021-08-02 21:26 UTC, AcapitalA commented
Based grudge PR

2021-08-03 08:11 UTC, TheChosenEvilOne commented
I would recommend leaving the default names out and instead just using the name json from the server for this.

2021-08-03 14:17 UTC, EdgeLordExe commented
it'd be funnier if you could 'dedicate' the vomit to someone, changing it's name (picture a mime making a post-modernist art piece which is just a pile of vomit named after the captain)

2021-08-04 07:24 UTC, Bucovineanu commented
I left the default names out and now you can dedicate them with a pen.

2021-08-04 09:11 UTC, TheChosenEvilOne requested changes

2021-08-04 09:11 UTC, TheChosenEvilOne commented on code/game/objects/effects/decals/cleanable/misc.dm
> +			names = json_decode(file2text(json_file))
```suggestion
		if(!fexists(json_file))
			return
		names = json_decode(file2text(json_file))
```

2021-08-04 09:11 UTC, TheChosenEvilOne commented on code/game/objects/effects/decals/cleanable/misc.dm
> +			return
```suggestion
		if(!t || !in_range(src, usr))
			return
```
you probably aren't going to keep vomit in your inventory.

2021-08-04 09:11 UTC, TheChosenEvilOne commented on code/game/objects/effects/decals/cleanable/misc.dm
> +			name = pick(names)
```suggestion
		if(names.len)
			name = pick(names)
```

2021-08-04 09:15 UTC, TheChosenEvilOne commented on code/game/objects/effects/decals/cleanable/misc.dm
> +			name = pick(names)
now that I think about this, the vomit list should be loaded only once.

2021-08-04 09:28 UTC, TheChosenEvilOne commented
mfw waiting for checks

2021-08-04 09:29 UTC, merged